name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_database
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        ports:
          - 3306:3306

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'  # Update to 8.3 if needed
        extensions: mbstring, exif, pcntl, bcmath
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create .env file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Set up environment file
      run: php artisan config:cache

    - name: Run migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_database
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: test_database
        DB_USERNAME: root
        DB_PASSWORD: root
      run: composer run test
